### ISSUE TITLE
Support the \n string mid-command

### ISSUE THREAD

**Issue by seanlaidlaw** [dzervas/fzf-command-bookmarks#1]
I have an awk command that has an action `{print "@"$name"\n"$seq"\n+\n"$qual}`. I wanted to add it as a command bookmark but it seems that when being parsed the \n despite being quoted was interpreted as a newline.

**Comment by dzervas** [comment]
Oh yes, that's the `echo -e` that I'm using internally...
Double escaping should work: `{print "@"$name\\n$seq\\n+\\n$qual}`

**Comment by seanlaidlaw** [comment]
Thanks for the reply, I did end up double escaping but when the command is selected, it enters the command line as doubly escaped so I have to manually go in removing the extra `\` before hitting enter. Is there a better way of doing this?

**Comment by dzervas** [comment]
Woah that's bad. I don't have any good ideas to solve this. I'll ask some friends around :shrug:

**Comment by dzervas** [comment]
@seanlaidlaw Hopefuly fixed! :)
